### PR TITLE
Drop the XPM version of the app icon

### PR DESCRIPTION
**Pull request by pinotree**
The application icon is already provided as PNG in different sizes, and installed in the global XDG hicolor icon theme. Hence, the XPM version of it can be dropped, as it is redundant.

### CODE REVIEW

**Comment by gottcode** [comment]
Does Debian no longer require an XPM version of the icon in addition to the PNGs? That is the only reason I added the XPM icon to my projects in the first place.

**Comment by pinotree** [comment]
Hmm, I don't think there was any requirement of XPM icon, at least not that I remember.

Maybe what you are thinking about was the old Debian menu system, which had XPM as "common denominator" to support as many DEs/WMs as possible; the old Debian menu system was formally deprecated 6 years ago, though (and tetzle has no Debian menu file since 2017).

**Comment by gottcode** [comment]
Interesting! One of the Debian packagers of my projects had described it to me as a requirement for the Debian package ages ago, so I added it.

If it was only for window managers, do any still need XPM icons? (I can't think of any, but then I mainly use KDE myself.) I want to make sure I'm not inconveniencing users. Otherwise, I am happy to merge this and also remove the XPM icon from all of my projects.

**Comment by pinotree** [comment]
> Interesting! One of the Debian packagers of my projects had described it to me as a requirement for the Debian package ages ago, so I added it.

Hard to say like this, unfortunately :-( My bet is on the old Debian menu though. If you find more details on this, I'll be glad to investigate more on it (I'm a DD, btw).

> If it was only for window managers, do any still need XPM icons?

That's a good question, and I don't know the answer. I use KDE Plasma myself too, which has been supporting XDG icons themes for a very long time. Maybe there could be some less used WM that does not support PNG; however, my thought is that, considering that the majority of modern/widely used applications do not ship XPM application icons, then not supporting PNG means having almost no icons in menus... assuming they can list that in menus (see desktop files).

**Comment by gottcode** [comment]
> > Interesting! One of the Debian packagers of my projects had described it to me as a requirement for the Debian package ages ago, so I added it.
> 
> Hard to say like this, unfortunately :-( My bet is on the old Debian menu though. If you find more details on this, I'll be glad to investigate more on it (I'm a DD, btw).

Sadly, I don't have all the emails from then, just my recollection. Hard drive failure and backups I hadn't been checking to make sure were good. :-(

> > If it was only for window managers, do any still need XPM icons?
> 
> That's a good question, and I don't know the answer. I use KDE Plasma myself too, which has been supporting XDG icons themes for a very long time. Maybe there could be some less used WM that does not support PNG; however, my thought is that, considering that the majority of modern/widely used applications do not ship XPM application icons, then not supporting PNG means having almost no icons in menus... assuming they can list that in menus (see desktop files).

That's a good point. If anybody complains, I could add it back. Or just point them to the git history.

**Comment by pinotree** [comment]
No problem -- feel free to contact/poke me anytime, in case of followups on this.

Thanks for merging!

**Pull request merged**
